import React from 'react';
import { ArrowRight, CalendarDays, Check, Layers3, UsersRound } from 'lucide-react';

const FEATURES = [
  { icon: CalendarDays, title: 'Calendário que calcula', text: 'Turnos, horas úteis e duração em um mesmo idioma de projeto.' },
  { icon: Layers3, title: 'Plano em movimento', text: 'Gantt, dependências e tarefas conectados em uma única visão.' },
  { icon: UsersRound, title: 'Equipe no mesmo lugar', text: 'Um workspace para owner e members acompanharem cada decisão.' },
];

export default function PublicLanding({ onStart }) {
  return (
    <main className="min-h-screen overflow-hidden bg-surface-0 text-text-1">
      <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <div className="flex items-center gap-3"><img src="/logo-premium.svg" alt="Projeta" className="size-9 rounded-[10px] object-cover shadow-elev-1" /><span className="text-sm font-semibold tracking-[0.18em]">PROJETA</span></div>
        <button type="button" onClick={onStart} className="rounded-[var(--radius-control)] border border-line-strong px-4 py-2 text-sm font-medium transition hover:border-brand hover:text-brand">Entrar</button>
      </header>
      <section className="mx-auto grid max-w-7xl items-center gap-14 px-6 pb-20 pt-14 lg:grid-cols-[0.85fr_1.15fr] lg:px-10 lg:pb-28 lg:pt-20">
        <div className="max-w-xl"><p className="mb-6 text-micro font-semibold uppercase tracking-[0.22em] text-brand">Planejamento com clareza</p><h1 className="max-w-2xl text-5xl font-semibold leading-[0.98] tracking-[-0.04em] sm:text-7xl">O plano inteiro. No ritmo real da equipe.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-text-2">Projeta transforma calendário, tarefas e decisões em um cronograma confiável quando o projeto começa a mudar.</p><button type="button" onClick={onStart} className="mt-9 inline-flex items-center gap-3 rounded-[var(--radius-control)] bg-brand px-6 py-3.5 text-sm font-semibold text-white shadow-elev-2 transition hover:bg-brand-hover">Começar agora <ArrowRight data-icon="inline-end" /></button><div className="mt-8 flex flex-wrap items-center gap-4 text-xs text-text-3"><span className="flex items-center gap-1.5"><Check className="text-brand" /> Workspace compartilhado</span><span className="flex items-center gap-1.5"><Check className="text-brand" /> Dados protegidos</span></div></div>
        <div className="relative lg:pt-8"><div className="overflow-hidden rounded-[18px] border border-line-strong bg-surface-1 shadow-elev-4"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><p className="text-micro uppercase tracking-[0.18em] text-text-3">Workspace / 04</p><p className="mt-1 text-sm font-medium">Parada de manutenção</p></div><span className="rounded-full bg-brand-soft px-3 py-1 text-micro font-semibold text-brand">AO VIVO</span></div><div className="grid grid-cols-[1.15fr_1fr] gap-5 p-5"><div className="flex flex-col gap-3">{['Preparação de campo', 'Bloqueio e liberação', 'Inspeção final', 'Retorno da operação'].map((item, index) => <div key={item} className="grid grid-cols-[1fr_0.8fr] items-center gap-3 border-b border-line pb-3"><div><div className="mb-1 flex items-center gap-2"><span className={`size-1.5 rounded-full ${index < 2 ? 'bg-brand' : 'bg-line-strong'}`} /><span className="text-xs text-text-2">{item}</span></div><span className="text-micro text-text-3">{index < 2 ? 'EM ANDAMENTO' : 'PLANEJADA'}</span></div><div className="h-2 overflow-hidden rounded-full bg-surface-3"><div className="h-full rounded-full bg-brand" style={{ width: `${[72, 46, 18, 5][index]}%` }} /></div></div>)}</div><div className="relative min-h-64 border-l border-line pl-5"><div className="mb-4 flex justify-between text-micro text-text-3"><span>08:00</span><span>12:00</span><span>17:00</span></div><div className="flex flex-col gap-7 pt-2">{[['w-[78%]', 'bg-brand'], ['w-[58%]', 'bg-sched-late'], ['w-[42%]', 'bg-sched-on-track'], ['w-[68%]', 'bg-sched-at-risk']].map(([width, color], index) => <div key={index} className="relative h-5 rounded-r-md bg-surface-3"><div className={`absolute inset-y-0 left-[${index * 6}%] rounded-r-md ${width} ${color}`} /></div>)}</div><div className="absolute bottom-2 left-5 right-0 border-t border-dashed border-brand/45" /></div></div></div><div className="absolute -bottom-7 -left-5 rounded-[var(--radius-card)] border border-line-strong bg-surface-1 px-4 py-3 shadow-elev-3 sm:left-8"><p className="text-micro uppercase tracking-[0.16em] text-text-3">Horas úteis hoje</p><p className="mt-1 text-xl font-semibold text-brand">07:30 <span className="text-xs font-normal text-text-3">/ 08:00</span></p></div></div>
      </section>
      <section className="mx-auto grid max-w-7xl gap-4 border-t border-line px-6 py-10 lg:grid-cols-3 lg:px-10">{FEATURES.map(({ icon: Icon, title, text }) => <div key={title} className="border-l border-brand/45 pl-4"><Icon className="mb-5 text-brand" /><h2 className="text-sm font-semibold">{title}</h2><p className="mt-2 max-w-xs text-sm leading-6 text-text-2">{text}</p></div>)}</section>
    </main>
  );
}
